import type { Metadata } from "next";
import "@/styles/globals.css";
import Navbar from "@/components/Navbar";
import Providers from "./providers";

export const metadata: Metadata = {
  title: "EduLens",
  description: "Generated by create next app",
  icons: {
    icon: "images/EduLensLogoNonBG.png",
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex justify-center w-screen h-screen bg-bgMain">
        <Providers>
          <Navbar/>
          <img src="/images/EduLensLogoNonBG.png" alt="EduLens Logo" className="fixed top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2"/>
          <div className="md:scale-100 scale-90">
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}