import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "EduLens",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex justify-center w-screen h-screen bg-bgMain">
        {children}
      </body>
    </html>
  );
}
